project:
  type: website
  output-dir: docs

website:
  title: "Vladimir R. Kostić"
  description: "Research homepage"
  site-url: "https://vladi-slk.github.io"
  output-dir: "_site"
  sitemap: true
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About Me
      - href: research.qmd
        text: Research
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cerulean
    css: styles.css
    toc: true
    include-in-header:
      - text: |
          <meta name="google-site-verification" content="ptvClKXwnY_tTDrTyVvQ__neQ7HujvLJxaNHgfGq-BI">

metadata:
  robots: index,follow
  og:
    image: imgs/mypic.png
    description: "Research homepage machine learning of dynmical systems and scientific applications."
  

